In [1]:
# เป็น lib ทำงานในรูปแบบออบเจคของ Array ชื่อ ndarray ที่คล้ายกับ List แต่เร็วและจัดการหน่วยความจำได้ดี

In [2]:
import numpy as np

zeros() สร้างแบบกำหนดมิติให้ทุกตัวเป็น 0

In [6]:
b = np.zeros([3,4], dtype=int) #dtype คือเราอยากให้เป็น type อะไร
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
c = np.ones([3,2])
c

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
d = np.full([3,2],9) #เลือกค่าได้
d

array([[9, 9],
       [9, 9],
       [9, 9]])

arrange() สร้างค่าจากเริ่มต้นไปยังค่าที่กำหนด

In [13]:
e = np.arange(10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
f = np.arange(1,11)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
g = np.arange(5,21,2)
g

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
h = np.arange(50,0,-5)
h

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5])

linspace() สร้างตัวเลขจากค่าเริ่มต้นไปค่าสิ้นสุดแบบระบุจำนวนที่การสร้างได้ (ถ้าไม่ระบุจำนวนจะเป็น 50) 

In [21]:
i = np.linspace(1,100,10)
i

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

eye() สร้างแนวทแยงมุมที่มีค่าเป็น 1 ที่เหลือเป็น 0 

In [23]:
j = np.eye(5)
j

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
j = np.eye(5,8,1) #metric 5x8 และให้ 1 ขยับไป1 หลัก
j

array([[0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.]])

empty() สร้าง ndarray แบบค่าสุ่ม

In [32]:
k = np.empty([5,5],dtype=int)
print(k)

[[4607182418800017408                   0                   0
                    0                   0]
 [                  0 4607182418800017408                   0
                    0                   0]
 [                  0                   0 4607182418800017408
                    0                   0]
 [                  0                   0                   0
  4607182418800017408                   0]
 [                  0                   0                   0
                    0 4607182418800017408]]


In [34]:
l = np.random.randint(100)
l

26

In [42]:
from numpy import random as rd
rd.randint(10)

5

In [43]:
rd.rand(3,4) #ค่าสุ่ม 0-1

array([[0.54785286, 0.10132555, 0.38963151, 0.55675958],
       [0.55891427, 0.71404823, 0.26976051, 0.57688598],
       [0.08718011, 0.6942673 , 0.44631427, 0.57371771]])

In [44]:
rd.randint(100,size=[2,3])

array([[35, 29, 16],
       [44, 42, 20]], dtype=int32)

choice() สร้างแบบสุ่มจากข้อมูลที่ตั้งไว้และสามารถตั้งความน่าจะเป็นได้

In [55]:
lst = [10,20,30,40,50]
a = rd.choice(lst, p=[0.5,0.2,0.1,0.1,0.1], size=[2,3])
print(a)

[[50 10 40]
 [50 10 30]]


shuffle() คือสลับตำแหน่ง

In [56]:
a = np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
rd.shuffle(a)
a

array([4, 6, 2, 3, 5, 8, 9, 0, 1, 7])

permutation() สลับค่าแต่เป็นการสร้างขึ้นมาใหม่ ตัวต้นฉบับยังคงเดิม เช่นเดียวกับ  tolower() toupper()

In [64]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
rd.permutation(b)

array([8, 7, 2, 4, 1, 0, 6, 9, 5, 3])

reshape() เปลี่ยนขนาดของ ndarray

In [69]:
p = np.arange(20)
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [82]:
print(p.reshape(4,5)) #ข้อมูลต้องสัมพันกันด้วยถึงจะ reshape ได้

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [87]:
p = rd.randint(100, size=[4,5])
print(p.reshape(4,5,-1)) # เอามาเรียงกลับเป็น 1D

[[[21]
  [99]
  [31]
  [76]
  [10]]

 [[83]
  [22]
  [70]
  [42]
  [30]]

 [[70]
  [ 3]
  [63]
  [35]
  [28]]

 [[59]
  [76]
  [ 3]
  [29]
  [46]]]


vectorization นำ array สองตัวที่มีมิติเท่ากันมาทำ operation

In [88]:
o = np.array([1,2,3,4,5])
s = np.array([4,5,6,7,8])
o+s

array([ 5,  7,  9, 11, 13])

In [89]:
y = [1,2,3,4,5]
z = [6,7,8,9,0]
y+z

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

Broadcasting นำ ndarray สองตัวที่มี 1 สมาชิก กับ n สมาชิก มาทำ operation

In [91]:
a = np.array([2,3,4,5])
b = np.array([5])
a*b

array([10, 15, 20, 25])

vectorize + broadcasting

In [95]:
a = np.arange(40).reshape(4,10)
print(a)
b = np.arange(4).reshape(4,1)
print(b)

print(a*b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
[[0]
 [1]
 [2]
 [3]]
[[  0   0   0   0   0   0   0   0   0   0]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 40  42  44  46  48  50  52  54  56  58]
 [ 90  93  96  99 102 105 108 111 114 117]]


Array indexing

In [96]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
a[-1,-1]

np.int64(11)

Index slicing

In [102]:
a[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [104]:
a[: : 2, 0 : 2]

array([[0, 1],
       [8, 9]])

In [106]:
a[ 1 : , 2 : ]

array([[ 6,  7],
       [10, 11]])

In [107]:
t = np.arange(20).reshape(4,5)
t

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [110]:
t[0 : : 3, 1 : : 2]

array([[ 1,  3],
       [16, 18]])

array join

In [112]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
join = np.concatenate([arr1, arr2])
join

array([1, 2, 3, 4, 5, 6, 7, 8])

array split